// Decompiled with JetBrains decompiler
// Type: go.Forms.DriverForm
// Assembly: go, Version=3.2.21.32438, Culture=neutral, PublicKeyToken=null
// MVID: B03B51CA-999B-45A2-A270-4FB8C2970A64
// Assembly location: C:\Users\rafalcelejewski\AppData\Local\Programs\GPro Organiser\Go.exe

using go.Enums;
using go.Utils;
using Properties;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace go.Forms
{
  public class DriverForm : Form
  {
    private Label label1;
    private Label label2;
    private Label label3;
    private Label label4;
    private Label label5;
    private Label label6;
    private Label label7;
    private Label label8;
    private Label label9;
    private Label label10;
    private Label label11;
    private Label label12;
    private Label label13;
    private Label label14;
    private Label label15;
    private Label label16;
    private Label label17;
    private Label label18;
    private Label label19;
    private Label label20;
    private Label label21;
    private Label label22;
    private TextBox textBoxtrophies;
    private TextBox textBoxnumGPs;
    private TextBox textBoxWins;
    private TextBox textBoxPodiums;
    private TextBox textBoxPoints;
    private TextBox textBoxPoles;
    private TextBox textBoxFastestLaps;
    private TextBox textBoxOverall;
    private TextBox textBoxConcentration;
    private TextBox textBoxTalent;
    private TextBox textBoxAggresiveness;
    private TextBox textBoxExperience;
    private TextBox textBoxTechnicalInsight;
    private TextBox textBoxStamina;
    private TextBox textBoxMotivation;
    private TextBox textBoxWeight;
    private TextBox textBoxAge;
    private TextBox textBoxSalary;
    private TextBox textBoxContract;
    private Label Races;
    private Button buttonExit;
    private TextBox textBoxAverage;
    private TextBox textBoxname;
    private TextBox textBoxnationality;
    private TextBox textBoxCharisma;
    private Label label23;
    private GroupBox groupBox1;
    private GroupBox groupBox2;
    private GroupBox groupBox3;
    private GroupBox groupBox4;
    private ToolTip toolTipOA;
    private ToolTip toolTipConc;
    private ToolTip toolTipTal;
    private ToolTip toolTipAgg;
    private ToolTip toolTipExp;
    private ToolTip toolTipTI;
    private ToolTip toolTipSta;
    private ToolTip toolTipCha;
    private ToolTip toolTipMot;
    private ToolTip ToolTipWei;
    private TextBox textBoxReputation;
    private Label label24;
    private ToolTip ToolTipRep;
    private TextBox textBoxEnergy;
    private Label label25;
    private IContainer components;

    public DriverForm(Driver5 d)
    {
      this.InitializeComponent();
      this.ShowInTaskbar = false;
      this.textBoxname.Text = d.name;
      this.textBoxnationality.Text = d.nationality;
      this.textBoxtrophies.Text = d.trophies.ToString();
      this.textBoxnumGPs.Text = d.numberOfGps.ToString();
      this.textBoxWins.Text = d.wins.ToString();
      this.textBoxPodiums.Text = d.podiums.ToString();
      this.textBoxPoints.Text = d.pointsScored.ToString();
      this.textBoxPoles.Text = d.polePositions.ToString();
      this.textBoxFastestLaps.Text = d.fastestLaps.ToString();
      this.textBoxAverage.Text = d.avPointsPerrace.ToString();
      this.textBoxOverall.Text = d.overall.ToString();
      this.textBoxConcentration.Text = d.concentration.ToString();
      this.textBoxTalent.Text = d.talent.ToString();
      this.textBoxAggresiveness.Text = d.aggresiveness.ToString();
      this.textBoxExperience.Text = d.experience.ToString();
      this.textBoxTechnicalInsight.Text = d.technicalInsight.ToString();
      this.textBoxStamina.Text = d.stamina.ToString();
      this.textBoxCharisma.Text = d.charisma.ToString();
      this.textBoxMotivation.Text = d.motivation.ToString();
      this.textBoxReputation.Text = d.reputation.ToString();
      this.textBoxEnergy.Text = d.energy.ToString();
      this.textBoxWeight.Text = d.weight.ToString();
      this.textBoxAge.Text = d.age.ToString();
      this.textBoxSalary.Text = EnumToString.Wage2String(d.salary);
      this.textBoxContract.Text = d.racesLeftOfContract.ToString();
      if (d.history.historyList.Count < 2)
        return;
      Date date = d.history.GetLastItem().date;
      for (int index = 0; index < d.history.historyList.Count; ++index)
      {
        DriverHistoryItem2 history = (DriverHistoryItem2) d.history.historyList[d.history.historyList.Count - 1 - index];
        if (history.date.race != date.race)
          break;
        ToolTip tip = new ToolTip();
        switch (history.driverinfo)
        {
          case DriverInfo.Overall:
            this.ColorTextBox(history, ref this.textBoxOverall, ref this.toolTipOA);
            break;
          case DriverInfo.Concentration:
            this.ColorTextBox(history, ref this.textBoxConcentration, ref this.toolTipConc);
            break;
          case DriverInfo.Talent:
            this.ColorTextBox(history, ref this.textBoxTalent, ref this.toolTipTal);
            break;
          case DriverInfo.Aggresiveness:
            this.ColorTextBox(history, ref this.textBoxAggresiveness, ref this.toolTipAgg);
            break;
          case DriverInfo.Experience:
            this.ColorTextBox(history, ref this.textBoxExperience, ref this.toolTipExp);
            break;
          case DriverInfo.TechnicalInsight:
            this.ColorTextBox(history, ref this.textBoxTechnicalInsight, ref this.toolTipTI);
            break;
          case DriverInfo.Stamina:
            this.ColorTextBox(history, ref this.textBoxStamina, ref this.toolTipSta);
            break;
          case DriverInfo.Charisma:
            this.ColorTextBox(history, ref this.textBoxCharisma, ref this.toolTipCha);
            break;
          case DriverInfo.Motivation:
            this.ColorTextBox(history, ref this.textBoxMotivation, ref this.toolTipMot);
            break;
          case DriverInfo.Weight:
            this.ColorTextBox(history, ref this.textBoxWeight, ref this.ToolTipWei);
            break;
          case DriverInfo.Trophies:
            this.ColorTextBox(history, ref this.textBoxtrophies, ref tip);
            break;
          case DriverInfo.Wins:
            this.ColorTextBox(history, ref this.textBoxWins, ref tip);
            break;
          case DriverInfo.Podiums:
            this.ColorTextBox(history, ref this.textBoxPodiums, ref tip);
            break;
          case DriverInfo.PointsScored:
            this.ColorTextBox(history, ref this.textBoxPoints, ref tip);
            break;
          case DriverInfo.PolePositions:
            this.ColorTextBox(history, ref this.textBoxPoles, ref tip);
            break;
          case DriverInfo.FastestLaps:
            this.ColorTextBox(history, ref this.textBoxFastestLaps, ref tip);
            break;
          case DriverInfo.AvPointsPerRace:
            this.ColorTextBox(history, ref this.textBoxAverage, ref tip);
            break;
          case DriverInfo.Salary:
            this.ColorTextBox(history, ref this.textBoxSalary, ref tip);
            break;
          case DriverInfo.RacesLeft:
            if (history.newValue < 4.0)
            {
              this.ColorTextBox(history, ref this.textBoxContract, ref tip);
              break;
            }
            break;
          case DriverInfo.Reputation:
            this.ColorTextBox(history, ref this.textBoxReputation, ref this.ToolTipRep);
            break;
        }
      }
    }

    private void ColorTextBox(DriverHistoryItem2 item, ref TextBox box, ref ToolTip tip)
    {
      if (item.oldValue < item.newValue)
      {
        box.BackColor = Color.Green;
        box.ForeColor = Color.White;
        box.Text += " ";
        box.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold);
        tip.SetToolTip((Control) box, "+" + ((double) (int) item.newValue - item.oldValue).ToString());
      }
      else
      {
        if (item.oldValue <= item.newValue)
          return;
        box.BackColor = Color.Red;
        box.ForeColor = Color.White;
        box.Text += " ";
        box.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold);
        tip.SetToolTip((Control) box, ((double) (int) item.newValue - item.oldValue).ToString());
      }
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.components = (IContainer) new System.ComponentModel.Container();
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (DriverForm));
      this.label1 = new Label();
      this.label2 = new Label();
      this.label3 = new Label();
      this.label4 = new Label();
      this.label5 = new Label();
      this.label6 = new Label();
      this.label7 = new Label();
      this.label8 = new Label();
      this.label9 = new Label();
      this.label10 = new Label();
      this.label11 = new Label();
      this.label12 = new Label();
      this.label13 = new Label();
      this.label14 = new Label();
      this.label15 = new Label();
      this.label16 = new Label();
      this.label17 = new Label();
      this.label18 = new Label();
      this.label19 = new Label();
      this.label20 = new Label();
      this.label21 = new Label();
      this.label22 = new Label();
      this.textBoxtrophies = new TextBox();
      this.textBoxnumGPs = new TextBox();
      this.textBoxWins = new TextBox();
      this.textBoxPodiums = new TextBox();
      this.textBoxPoints = new TextBox();
      this.textBoxPoles = new TextBox();
      this.textBoxFastestLaps = new TextBox();
      this.textBoxOverall = new TextBox();
      this.textBoxConcentration = new TextBox();
      this.textBoxTalent = new TextBox();
      this.textBoxAggresiveness = new TextBox();
      this.textBoxExperience = new TextBox();
      this.textBoxTechnicalInsight = new TextBox();
      this.textBoxStamina = new TextBox();
      this.textBoxMotivation = new TextBox();
      this.textBoxWeight = new TextBox();
      this.textBoxAge = new TextBox();
      this.textBoxSalary = new TextBox();
      this.textBoxContract = new TextBox();
      this.Races = new Label();
      this.textBoxname = new TextBox();
      this.textBoxnationality = new TextBox();
      this.buttonExit = new Button();
      this.textBoxAverage = new TextBox();
      this.textBoxCharisma = new TextBox();
      this.label23 = new Label();
      this.groupBox1 = new GroupBox();
      this.groupBox2 = new GroupBox();
      this.textBoxReputation = new TextBox();
      this.label24 = new Label();
      this.groupBox3 = new GroupBox();
      this.groupBox4 = new GroupBox();
      this.toolTipOA = new ToolTip(this.components);
      this.toolTipConc = new ToolTip(this.components);
      this.toolTipTal = new ToolTip(this.components);
      this.toolTipAgg = new ToolTip(this.components);
      this.toolTipExp = new ToolTip(this.components);
      this.toolTipTI = new ToolTip(this.components);
      this.toolTipSta = new ToolTip(this.components);
      this.toolTipCha = new ToolTip(this.components);
      this.toolTipMot = new ToolTip(this.components);
      this.ToolTipWei = new ToolTip(this.components);
      this.ToolTipRep = new ToolTip(this.components);
      this.textBoxEnergy = new TextBox();
      this.label25 = new Label();
      this.groupBox2.SuspendLayout();
      this.SuspendLayout();
      this.label1.Location = new Point(8, 16);
      this.label1.Name = "label1";
      this.label1.Size = new Size(48, 16);
      this.label1.TabIndex = 0;
      this.label1.Text = "Name";
      this.label2.Location = new Point(8, 32);
      this.label2.Name = "label2";
      this.label2.Size = new Size(64, 16);
      this.label2.TabIndex = 1;
      this.label2.Text = "Nationality";
      this.label3.Location = new Point(16, 80);
      this.label3.Name = "label3";
      this.label3.Size = new Size(64, 16);
      this.label3.TabIndex = 2;
      this.label3.Text = "Trophies";
      this.label4.Location = new Point(16, 96);
      this.label4.Name = "label4";
      this.label4.Size = new Size(88, 16);
      this.label4.TabIndex = 3;
      this.label4.Text = "Number of GPs";
      this.label5.Location = new Point(16, 112);
      this.label5.Name = "label5";
      this.label5.Size = new Size(64, 16);
      this.label5.TabIndex = 4;
      this.label5.Text = "Wins";
      this.label6.Location = new Point(16, 128);
      this.label6.Name = "label6";
      this.label6.Size = new Size(64, 16);
      this.label6.TabIndex = 5;
      this.label6.Text = "Podiums";
      this.label7.Location = new Point(16, 144);
      this.label7.Name = "label7";
      this.label7.Size = new Size(80, 16);
      this.label7.TabIndex = 6;
      this.label7.Text = "Points Scored";
      this.label8.Location = new Point(16, 160);
      this.label8.Name = "label8";
      this.label8.Size = new Size(80, 16);
      this.label8.TabIndex = 7;
      this.label8.Text = "Pole Positions";
      this.label9.Location = new Point(16, 176);
      this.label9.Name = "label9";
      this.label9.Size = new Size(72, 16);
      this.label9.TabIndex = 8;
      this.label9.Text = "Fastest Laps";
      this.label10.Location = new Point(16, 192);
      this.label10.Name = "label10";
      this.label10.Size = new Size(64, 16);
      this.label10.TabIndex = 9;
      this.label10.Text = "Av pts/race";
      this.label11.Location = new Point(152, 80);
      this.label11.Name = "label11";
      this.label11.Size = new Size(64, 16);
      this.label11.TabIndex = 10;
      this.label11.Text = "Overall";
      this.label12.Location = new Point(152, 96);
      this.label12.Name = "label12";
      this.label12.Size = new Size(80, 16);
      this.label12.TabIndex = 11;
      this.label12.Text = "Concentration";
      this.label13.Location = new Point(152, 112);
      this.label13.Name = "label13";
      this.label13.Size = new Size(80, 16);
      this.label13.TabIndex = 12;
      this.label13.Text = "Talent";
      this.label14.Location = new Point(152, 128);
      this.label14.Name = "label14";
      this.label14.Size = new Size(80, 16);
      this.label14.TabIndex = 13;
      this.label14.Text = "Aggresiveness";
      this.label15.Location = new Point(152, 144);
      this.label15.Name = "label15";
      this.label15.Size = new Size(80, 16);
      this.label15.TabIndex = 14;
      this.label15.Text = "Experience";
      this.label16.Location = new Point(152, 160);
      this.label16.Name = "label16";
      this.label16.Size = new Size(96, 16);
      this.label16.TabIndex = 15;
      this.label16.Text = "Technical Insight";
      this.label17.Location = new Point(152, 176);
      this.label17.Name = "label17";
      this.label17.Size = new Size(80, 16);
      this.label17.TabIndex = 16;
      this.label17.Text = "Stamina";
      this.label18.Location = new Point(152, 208);
      this.label18.Name = "label18";
      this.label18.Size = new Size(80, 16);
      this.label18.TabIndex = 17;
      this.label18.Text = "Motivation";
      this.label19.Location = new Point(304, 80);
      this.label19.Name = "label19";
      this.label19.Size = new Size(80, 16);
      this.label19.TabIndex = 18;
      this.label19.Text = "Salary";
      this.label20.Location = new Point(304, 144);
      this.label20.Name = "label20";
      this.label20.Size = new Size(48, 16);
      this.label20.TabIndex = 19;
      this.label20.Text = "Weight";
      this.label21.Location = new Point(304, 160);
      this.label21.Name = "label21";
      this.label21.Size = new Size(40, 16);
      this.label21.TabIndex = 20;
      this.label21.Text = "Age";
      this.label22.Location = new Point(304, 96);
      this.label22.Name = "label22";
      this.label22.Size = new Size(88, 16);
      this.label22.TabIndex = 21;
      this.label22.Text = "Contract Length";
      this.textBoxtrophies.BorderStyle = BorderStyle.None;
      this.textBoxtrophies.Location = new Point(96, 80);
      this.textBoxtrophies.Name = "textBoxtrophies";
      this.textBoxtrophies.ReadOnly = true;
      this.textBoxtrophies.Size = new Size(24, 13);
      this.textBoxtrophies.TabIndex = 22;
      this.textBoxtrophies.TabStop = false;
      this.textBoxtrophies.Text = "999";
      this.textBoxtrophies.TextAlign = HorizontalAlignment.Right;
      this.textBoxnumGPs.BorderStyle = BorderStyle.None;
      this.textBoxnumGPs.Location = new Point(96, 96);
      this.textBoxnumGPs.Name = "textBoxnumGPs";
      this.textBoxnumGPs.ReadOnly = true;
      this.textBoxnumGPs.Size = new Size(24, 13);
      this.textBoxnumGPs.TabIndex = 23;
      this.textBoxnumGPs.TabStop = false;
      this.textBoxnumGPs.Text = "999";
      this.textBoxnumGPs.TextAlign = HorizontalAlignment.Right;
      this.textBoxWins.BorderStyle = BorderStyle.None;
      this.textBoxWins.Location = new Point(96, 112);
      this.textBoxWins.Name = "textBoxWins";
      this.textBoxWins.ReadOnly = true;
      this.textBoxWins.Size = new Size(24, 13);
      this.textBoxWins.TabIndex = 24;
      this.textBoxWins.TabStop = false;
      this.textBoxWins.Text = "999";
      this.textBoxWins.TextAlign = HorizontalAlignment.Right;
      this.textBoxPodiums.BorderStyle = BorderStyle.None;
      this.textBoxPodiums.Location = new Point(96, 128);
      this.textBoxPodiums.Name = "textBoxPodiums";
      this.textBoxPodiums.ReadOnly = true;
      this.textBoxPodiums.Size = new Size(24, 13);
      this.textBoxPodiums.TabIndex = 25;
      this.textBoxPodiums.TabStop = false;
      this.textBoxPodiums.Text = "999";
      this.textBoxPodiums.TextAlign = HorizontalAlignment.Right;
      this.textBoxPoints.BorderStyle = BorderStyle.None;
      this.textBoxPoints.Location = new Point(96, 144);
      this.textBoxPoints.Name = "textBoxPoints";
      this.textBoxPoints.ReadOnly = true;
      this.textBoxPoints.Size = new Size(24, 13);
      this.textBoxPoints.TabIndex = 26;
      this.textBoxPoints.TabStop = false;
      this.textBoxPoints.Text = "999";
      this.textBoxPoints.TextAlign = HorizontalAlignment.Right;
      this.textBoxPoles.BorderStyle = BorderStyle.None;
      this.textBoxPoles.Location = new Point(96, 160);
      this.textBoxPoles.Name = "textBoxPoles";
      this.textBoxPoles.ReadOnly = true;
      this.textBoxPoles.Size = new Size(24, 13);
      this.textBoxPoles.TabIndex = 27;
      this.textBoxPoles.TabStop = false;
      this.textBoxPoles.Text = "999";
      this.textBoxPoles.TextAlign = HorizontalAlignment.Right;
      this.textBoxFastestLaps.BorderStyle = BorderStyle.None;
      this.textBoxFastestLaps.Location = new Point(96, 176);
      this.textBoxFastestLaps.Name = "textBoxFastestLaps";
      this.textBoxFastestLaps.ReadOnly = true;
      this.textBoxFastestLaps.Size = new Size(24, 13);
      this.textBoxFastestLaps.TabIndex = 28;
      this.textBoxFastestLaps.TabStop = false;
      this.textBoxFastestLaps.Text = "999";
      this.textBoxFastestLaps.TextAlign = HorizontalAlignment.Right;
      this.textBoxOverall.BorderStyle = BorderStyle.None;
      this.textBoxOverall.Location = new Point(248, 80);
      this.textBoxOverall.Name = "textBoxOverall";
      this.textBoxOverall.ReadOnly = true;
      this.textBoxOverall.Size = new Size(24, 13);
      this.textBoxOverall.TabIndex = 29;
      this.textBoxOverall.TabStop = false;
      this.textBoxOverall.Text = "999";
      this.textBoxOverall.TextAlign = HorizontalAlignment.Right;
      this.textBoxConcentration.BorderStyle = BorderStyle.None;
      this.textBoxConcentration.Location = new Point(248, 96);
      this.textBoxConcentration.Name = "textBoxConcentration";
      this.textBoxConcentration.ReadOnly = true;
      this.textBoxConcentration.Size = new Size(24, 13);
      this.textBoxConcentration.TabIndex = 30;
      this.textBoxConcentration.TabStop = false;
      this.textBoxConcentration.Text = "999";
      this.textBoxConcentration.TextAlign = HorizontalAlignment.Right;
      this.textBoxTalent.BorderStyle = BorderStyle.None;
      this.textBoxTalent.Location = new Point(248, 112);
      this.textBoxTalent.Name = "textBoxTalent";
      this.textBoxTalent.ReadOnly = true;
      this.textBoxTalent.Size = new Size(24, 13);
      this.textBoxTalent.TabIndex = 31;
      this.textBoxTalent.TabStop = false;
      this.textBoxTalent.Text = "999";
      this.textBoxTalent.TextAlign = HorizontalAlignment.Right;
      this.textBoxAggresiveness.BorderStyle = BorderStyle.None;
      this.textBoxAggresiveness.Location = new Point(248, 128);
      this.textBoxAggresiveness.Name = "textBoxAggresiveness";
      this.textBoxAggresiveness.ReadOnly = true;
      this.textBoxAggresiveness.Size = new Size(24, 13);
      this.textBoxAggresiveness.TabIndex = 32;
      this.textBoxAggresiveness.TabStop = false;
      this.textBoxAggresiveness.Text = "999";
      this.textBoxAggresiveness.TextAlign = HorizontalAlignment.Right;
      this.textBoxExperience.BorderStyle = BorderStyle.None;
      this.textBoxExperience.Location = new Point(248, 144);
      this.textBoxExperience.Name = "textBoxExperience";
      this.textBoxExperience.ReadOnly = true;
      this.textBoxExperience.Size = new Size(24, 13);
      this.textBoxExperience.TabIndex = 33;
      this.textBoxExperience.TabStop = false;
      this.textBoxExperience.Text = "999";
      this.textBoxExperience.TextAlign = HorizontalAlignment.Right;
      this.textBoxTechnicalInsight.BorderStyle = BorderStyle.None;
      this.textBoxTechnicalInsight.Location = new Point(248, 160);
      this.textBoxTechnicalInsight.Name = "textBoxTechnicalInsight";
      this.textBoxTechnicalInsight.ReadOnly = true;
      this.textBoxTechnicalInsight.Size = new Size(24, 13);
      this.textBoxTechnicalInsight.TabIndex = 34;
      this.textBoxTechnicalInsight.TabStop = false;
      this.textBoxTechnicalInsight.Text = "999";
      this.textBoxTechnicalInsight.TextAlign = HorizontalAlignment.Right;
      this.textBoxStamina.BorderStyle = BorderStyle.None;
      this.textBoxStamina.Location = new Point(248, 176);
      this.textBoxStamina.Name = "textBoxStamina";
      this.textBoxStamina.ReadOnly = true;
      this.textBoxStamina.Size = new Size(24, 13);
      this.textBoxStamina.TabIndex = 35;
      this.textBoxStamina.TabStop = false;
      this.textBoxStamina.Text = "999";
      this.textBoxStamina.TextAlign = HorizontalAlignment.Right;
      this.textBoxMotivation.BorderStyle = BorderStyle.None;
      this.textBoxMotivation.Location = new Point(248, 208);
      this.textBoxMotivation.Name = "textBoxMotivation";
      this.textBoxMotivation.ReadOnly = true;
      this.textBoxMotivation.Size = new Size(24, 13);
      this.textBoxMotivation.TabIndex = 36;
      this.textBoxMotivation.TabStop = false;
      this.textBoxMotivation.Text = "999";
      this.textBoxMotivation.TextAlign = HorizontalAlignment.Right;
      this.textBoxWeight.BorderStyle = BorderStyle.None;
      this.textBoxWeight.Location = new Point(352, 144);
      this.textBoxWeight.Name = "textBoxWeight";
      this.textBoxWeight.ReadOnly = true;
      this.textBoxWeight.Size = new Size(24, 13);
      this.textBoxWeight.TabIndex = 37;
      this.textBoxWeight.TabStop = false;
      this.textBoxWeight.Text = "999";
      this.textBoxWeight.TextAlign = HorizontalAlignment.Right;
      this.textBoxAge.BorderStyle = BorderStyle.None;
      this.textBoxAge.Location = new Point(352, 160);
      this.textBoxAge.Name = "textBoxAge";
      this.textBoxAge.ReadOnly = true;
      this.textBoxAge.Size = new Size(24, 13);
      this.textBoxAge.TabIndex = 38;
      this.textBoxAge.TabStop = false;
      this.textBoxAge.Text = "999";
      this.textBoxAge.TextAlign = HorizontalAlignment.Right;
      this.textBoxSalary.BorderStyle = BorderStyle.None;
      this.textBoxSalary.Location = new Point(376, 80);
      this.textBoxSalary.Name = "textBoxSalary";
      this.textBoxSalary.ReadOnly = true;
      this.textBoxSalary.Size = new Size(72, 13);
      this.textBoxSalary.TabIndex = 39;
      this.textBoxSalary.TabStop = false;
      this.textBoxSalary.Text = "999";
      this.textBoxSalary.TextAlign = HorizontalAlignment.Right;
      this.textBoxContract.BorderStyle = BorderStyle.None;
      this.textBoxContract.Location = new Point(392, 96);
      this.textBoxContract.Name = "textBoxContract";
      this.textBoxContract.ReadOnly = true;
      this.textBoxContract.Size = new Size(24, 13);
      this.textBoxContract.TabIndex = 40;
      this.textBoxContract.TabStop = false;
      this.textBoxContract.Text = "999";
      this.textBoxContract.TextAlign = HorizontalAlignment.Right;
      this.Races.Location = new Point(424, 96);
      this.Races.Name = "Races";
      this.Races.Size = new Size(32, 16);
      this.Races.TabIndex = 41;
      this.Races.Text = "races";
      this.textBoxname.BorderStyle = BorderStyle.None;
      this.textBoxname.Location = new Point(64, 16);
      this.textBoxname.Name = "textBoxname";
      this.textBoxname.ReadOnly = true;
      this.textBoxname.Size = new Size(120, 13);
      this.textBoxname.TabIndex = 42;
      this.textBoxname.TabStop = false;
      this.textBoxname.Text = "999";
      this.textBoxnationality.BorderStyle = BorderStyle.None;
      this.textBoxnationality.Location = new Point(64, 32);
      this.textBoxnationality.Name = "textBoxnationality";
      this.textBoxnationality.ReadOnly = true;
      this.textBoxnationality.Size = new Size(120, 13);
      this.textBoxnationality.TabIndex = 43;
      this.textBoxnationality.TabStop = false;
      this.textBoxnationality.Text = "999";
      this.buttonExit.DialogResult = DialogResult.Cancel;
      this.buttonExit.Location = new Point(408, 208);
      this.buttonExit.Name = "buttonExit";
      this.buttonExit.Size = new Size(56, 24);
      this.buttonExit.TabIndex = 44;
      this.buttonExit.Text = "Exit";
      this.buttonExit.Click += new EventHandler(this.buttonExit_Click);
      this.textBoxAverage.BorderStyle = BorderStyle.None;
      this.textBoxAverage.Location = new Point(88, 192);
      this.textBoxAverage.Name = "textBoxAverage";
      this.textBoxAverage.ReadOnly = true;
      this.textBoxAverage.Size = new Size(32, 13);
      this.textBoxAverage.TabIndex = 45;
      this.textBoxAverage.TabStop = false;
      this.textBoxAverage.Text = "999";
      this.textBoxAverage.TextAlign = HorizontalAlignment.Right;
      this.textBoxCharisma.BorderStyle = BorderStyle.None;
      this.textBoxCharisma.Location = new Point(248, 192);
      this.textBoxCharisma.Name = "textBoxCharisma";
      this.textBoxCharisma.ReadOnly = true;
      this.textBoxCharisma.Size = new Size(24, 13);
      this.textBoxCharisma.TabIndex = 47;
      this.textBoxCharisma.TabStop = false;
      this.textBoxCharisma.Text = "999";
      this.textBoxCharisma.TextAlign = HorizontalAlignment.Right;
      this.label23.Location = new Point(152, 192);
      this.label23.Name = "label23";
      this.label23.Size = new Size(80, 16);
      this.label23.TabIndex = 46;
      this.label23.Text = "Charisma";
      this.groupBox1.Location = new Point(8, 56);
      this.groupBox1.Name = "groupBox1";
      this.groupBox1.Size = new Size(128, 160);
      this.groupBox1.TabIndex = 48;
      this.groupBox1.TabStop = false;
      this.groupBox1.Text = "Career";
      this.groupBox2.Controls.Add((Control) this.textBoxReputation);
      this.groupBox2.Controls.Add((Control) this.label24);
      this.groupBox2.Location = new Point(144, 56);
      this.groupBox2.Name = "groupBox2";
      this.groupBox2.Size = new Size(144, 199);
      this.groupBox2.TabIndex = 49;
      this.groupBox2.TabStop = false;
      this.groupBox2.Text = "Skills";
      this.textBoxReputation.BorderStyle = BorderStyle.None;
      this.textBoxReputation.Location = new Point(104, 168);
      this.textBoxReputation.Name = "textBoxReputation";
      this.textBoxReputation.ReadOnly = true;
      this.textBoxReputation.Size = new Size(24, 13);
      this.textBoxReputation.TabIndex = 52;
      this.textBoxReputation.TabStop = false;
      this.textBoxReputation.Text = "999";
      this.textBoxReputation.TextAlign = HorizontalAlignment.Right;
      this.label24.Location = new Point(8, 168);
      this.label24.Name = "label24";
      this.label24.Size = new Size(80, 16);
      this.label24.TabIndex = 52;
      this.label24.Text = "Reputation";
      this.groupBox3.Location = new Point(296, 56);
      this.groupBox3.Name = "groupBox3";
      this.groupBox3.Size = new Size(168, 64);
      this.groupBox3.TabIndex = 50;
      this.groupBox3.TabStop = false;
      this.groupBox3.Text = "Contract Details";
      this.groupBox4.Location = new Point(296, 128);
      this.groupBox4.Name = "groupBox4";
      this.groupBox4.Size = new Size(96, 56);
      this.groupBox4.TabIndex = 51;
      this.groupBox4.TabStop = false;
      this.textBoxEnergy.BorderStyle = BorderStyle.None;
      this.textBoxEnergy.Location = new Point(400, 29);
      this.textBoxEnergy.Name = "textBoxEnergy";
      this.textBoxEnergy.ReadOnly = true;
      this.textBoxEnergy.Size = new Size(24, 13);
      this.textBoxEnergy.TabIndex = 53;
      this.textBoxEnergy.TabStop = false;
      this.textBoxEnergy.Text = "999";
      this.textBoxEnergy.TextAlign = HorizontalAlignment.Right;
      this.label25.Location = new Point(304, 29);
      this.label25.Name = "label25";
      this.label25.Size = new Size(80, 16);
      this.label25.TabIndex = 52;
      this.label25.Text = "Energy";
      this.AcceptButton = (IButtonControl) this.buttonExit;
      this.AutoScaleBaseSize = new Size(5, 13);
      this.CancelButton = (IButtonControl) this.buttonExit;
      this.ClientSize = new Size(472, 267);
      this.Controls.Add((Control) this.textBoxEnergy);
      this.Controls.Add((Control) this.label25);
      this.Controls.Add((Control) this.textBoxCharisma);
      this.Controls.Add((Control) this.textBoxAverage);
      this.Controls.Add((Control) this.textBoxnationality);
      this.Controls.Add((Control) this.textBoxname);
      this.Controls.Add((Control) this.textBoxContract);
      this.Controls.Add((Control) this.textBoxSalary);
      this.Controls.Add((Control) this.textBoxAge);
      this.Controls.Add((Control) this.textBoxWeight);
      this.Controls.Add((Control) this.textBoxMotivation);
      this.Controls.Add((Control) this.textBoxStamina);
      this.Controls.Add((Control) this.textBoxTechnicalInsight);
      this.Controls.Add((Control) this.textBoxExperience);
      this.Controls.Add((Control) this.textBoxAggresiveness);
      this.Controls.Add((Control) this.textBoxTalent);
      this.Controls.Add((Control) this.textBoxConcentration);
      this.Controls.Add((Control) this.textBoxOverall);
      this.Controls.Add((Control) this.textBoxFastestLaps);
      this.Controls.Add((Control) this.textBoxPoles);
      this.Controls.Add((Control) this.textBoxPoints);
      this.Controls.Add((Control) this.textBoxPodiums);
      this.Controls.Add((Control) this.textBoxWins);
      this.Controls.Add((Control) this.textBoxnumGPs);
      this.Controls.Add((Control) this.textBoxtrophies);
      this.Controls.Add((Control) this.label23);
      this.Controls.Add((Control) this.buttonExit);
      this.Controls.Add((Control) this.Races);
      this.Controls.Add((Control) this.label22);
      this.Controls.Add((Control) this.label21);
      this.Controls.Add((Control) this.label20);
      this.Controls.Add((Control) this.label19);
      this.Controls.Add((Control) this.label18);
      this.Controls.Add((Control) this.label17);
      this.Controls.Add((Control) this.label16);
      this.Controls.Add((Control) this.label15);
      this.Controls.Add((Control) this.label14);
      this.Controls.Add((Control) this.label13);
      this.Controls.Add((Control) this.label12);
      this.Controls.Add((Control) this.label11);
      this.Controls.Add((Control) this.label10);
      this.Controls.Add((Control) this.label9);
      this.Controls.Add((Control) this.label8);
      this.Controls.Add((Control) this.label7);
      this.Controls.Add((Control) this.label6);
      this.Controls.Add((Control) this.label5);
      this.Controls.Add((Control) this.label4);
      this.Controls.Add((Control) this.label3);
      this.Controls.Add((Control) this.label2);
      this.Controls.Add((Control) this.label1);
      this.Controls.Add((Control) this.groupBox1);
      this.Controls.Add((Control) this.groupBox2);
      this.Controls.Add((Control) this.groupBox3);
      this.Controls.Add((Control) this.groupBox4);
      this.Icon = Resources.Car;
      this.Name = nameof (DriverForm);
      this.Text = "Driver";
      this.groupBox2.ResumeLayout(false);
      this.groupBox2.PerformLayout();
      this.ResumeLayout(false);
      this.PerformLayout();
    }

    private void buttonExit_Click(object sender, EventArgs e) => this.Close();
  }
}
