name: Build and Release GO

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore Go.sln

      - name: Build solution
        run: msbuild Go.sln /p:Configuration=Release

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path bin\Release\* -DestinationPath GPRO-Organizer-${{ github.ref_name }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: GPRO Organizer ${{ github.ref_name }}
          files: GPRO-Organizer-${{ github.ref_name }}.zip