name: Build and Release GO

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Extract version
        id: version
        shell: pwsh
        run: |
          $version = Select-String -Path AssemblyInfo.cs -Pattern 'AssemblyFileVersion\("(.+)"\)' | ForEach-Object {
            $_.Matches[0].Groups[1].Value
          }

          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Restore NuGet packages
        run: nuget restore Go.sln

      - name: Build solution
        run: msbuild Go.sln /p:Configuration=Release

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path bin\Release\* -DestinationPath GPRO-Organizer-v${env:VERSION}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          name: GPRO Organizer v${{ env.VERSION }}
          files: GPRO-Organizer-v${{ env.VERSION }}.zip