name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore Go.sln

      - name: Build solution
        run: msbuild Go.sln /p:Configuration=Release

      - name: Show build output
        run: dir /s bin\Release

      - name: Create ZIP package
        shell: powershell
        run: |
          Compress-Archive `
            -Path "bin\Release\*" `
            -DestinationPath "GPRO-Organiser.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GPRO-Organiser
          path: GPRO-Organiser.zip